name: Terraform AWS Workflow

on:
  workflow_dispatch:
    inputs:
      apply_terraform:
        description: 'Apply Terraform changes'
        required: true
        default: 'false'

jobs:
  terraform:
    name: Terraform Init, Validate, Plan, Infracost, Checkov, and Apply
    runs-on: ubuntu-latest

    env:
      TF_VERSION: 1.3.0
      INFRACOST_VERSION: 0.9.5
      CHECKOV_VERSION: 2.0.989

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=plan.tfplan

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Run Infracost
        run: infracost breakdown --path plan.tfplan --format json --out-file infracost.json

      - name: Upload Infracost Report
        uses: actions/upload-artifact@v3
        with:
          name: infracost-report
          path: infracost.json

#      - name: Checkov GitHub Action
#        uses: bridgecrewio/checkov-action@v12
#        with:
#          output_format: cli,sarif
#          output_file_path: console,results.sarif

      - name: Terraform Apply
        if: ${{ github.event.inputs.apply_terraform == 'true' }}
        run: terraform apply -auto-approve plan.tfplan
